version: "2"

services:

  replaycode-ocr:
    build:
      context: ./replaycode-ocr
    container_name: replaycode-ocr
    volumes:
      - ./replaycode-ocr/output:/app/output
    stdin_open: true
    tty: true