services:

  replaycode-ocr:
    build:
      context: ./replaycode-ocr
    container_name: replaycode-ocr
    volumes:
      - ./replaycode-ocr/output:/app/output
      - ./replaycode-ocr/model-data:/app/model-data
    stdin_open: true
    tty: true
    # uncomment this line in prod
    #restart: unless-stopped
